### PR TITLE
Fix typo `ethUtil` to `utils`

### PR DESCRIPTION
**Pull request by XertroV**
Seems like a typo; changed locally and everything works for me, so presumably a fix. Please check.

### CODE REVIEW

**Comment by davesag** [comment]
Looks like that will fix #13

**Comment by ameensol** [comment]
Waiting on this, please merge at earliest opportunity.

**Comment by iurimatias** [comment]
+1 will merge and release tonight

**Comment by ameensol** [comment]
Thanks!

**Comment by iurimatias** [comment]
0.5.1

**Pull request merged**
